ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080

ktorm:
    database:
        url: "jdbc:mysql://localhost:3306/ktorm"
        driver: "com.mysql.cj.jdbc.Driver"
        username: "root"
        password: "admin"
